### PR TITLE
fix: displaying certain objects cause error. try displaying them first

### LINKED ISSUE #49: running this julia code causes REPLsmuggler to crash
`a = [(1,2),(3,4)]'`

this throws a MethodError if simply run in a julia REPL

however when sent through smuggler it throws the error and causes REPLSmuggler to crash as well

### PR DESCRIPTION
**Pull request by ArbitRandomUser**
attempt to fix #49

### CODE REVIEW

File: src/eval.jl [hunk 1]
```diff
@@ -132,7 +132,11 @@ function evaluate_entry(session, msgid, file, line, value, repl = Base.active_re
             if isnothing(index_mime)
                 io = IOBuffer()
                 ctx = IOContext(io, [k => v for (k, v) in session.sessionparams["iocontext"]]...)
-                Base.invokelatest(show, ctx, MIME("text/plain"), first(repl_response))
+                try
+                    Base.invokelatest(show, ctx, MIME("text/plain"), first(repl_response))
+                catch exception
+                    nothing
```
Comment (Klafyvel) [inline src/eval.jl:138]: Shouldn't we notify the user that something went wrong here? Either by sending an error report to the editor, or at least displaying a warning?

**Review by Klafyvel — COMMENTED** [review]
Hi, Thanks for looking into that, I have one question on how we should handle erroring in show.

File: src/eval.jl (hunk 1 above)
Comment (ArbitRandomUser) [reply src/eval.jl:138]: the Error and trace that repl would show still gets put out on the repl when such code (as mentioned in #49) is smuggled.
It gets handled inside `show` . So printing the error again would be redundant.

We could handle it with a warning and a Diagnostic message on the vim side. I'll take a look into how that can be handled.

Comment (Klafyvel) [reply src/eval.jl:138]: I see, sorry for missing your point. I think it's Ok to silently ignore then. Can you simply add a comment explaining why it's OK, so I don't freak out in the future when I'll have forgotten why it is OK? :)

Comment (Klafyvel) [reply src/eval.jl:138]: I think you can add the same safeguard [line 144](https://github.com/Klafyvel/REPLSmuggler.jl/pull/50/files#diff-60fedf1f907ac122cd179cc941b0a6c08297e2298fb881399bf41a3e1ee1dc84R144) when saving the output to a file. This time it should not be silent, but have a `@warn` instead.

Comment (ArbitRandomUser) [reply src/eval.jl:145]: Forgot to add the warm , will do it in a while and push.

**Review by Klafyvel — APPROVED** [review]
